name: Sample proposal
description: Make a proposal to add a new sample
title: '[Sample]: '
labels: ['Needs: Triage :mag:', 'sample']
body:
  - type: markdown
    attributes:
      value: |
        Fill out this form below to suggest a new sample.
  - type: dropdown
    id: exiting-sample-check
    attributes:
      label: Have you checked this sample does not already exist in the repository?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    id: why-the-module
    attributes:
      label: Why is the sample needed?
      description: Explain why the sample is needed. If there is a existing sample, explain why it cannot be updated to meet your needs and why a new one must be created.
    validations:
      required: true
  - type: input
    id: sample-path
    attributes:
      label: Sample path
      description: The path to the new sample.
      placeholder: samples/azure/example
    validations:
      required: true
  - type: textarea
    id: sample-description
    attributes:
      label: Describe the sample
      description: A clear and concise description of the sample.
    validations:
      required: true
